version: '3.8'

services:
  homicsx:
    build: 
      context: .
      dockerfile: Dockerfile
    image: homicsx:latest
    container_name: homicsx
    ports:
      - "8888:8888"
    volumes:
      - .:/root/HomiCSx
      - ./workspace:/root/workspace
      - ./examples:/root/examples
    working_dir: /root/workspace
    environment:
      - JUPTER_ENABLE_LAB=yes
      - PYTHONPATH=/root/HomiCSx
    stdin_open: true
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --notebook-dir=/root
