name: homicsx_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fenics-dolfinx=0.9.0
  - mpich=4.2.3
  - pyvista=0.44.1
  - conda-forge::dolfinx_mpc=0.9.0
  - meshio=5.3.5
  - ipykernel=6.29.5
  - numpy=1.26.1
  - matplotlib=3.8.0
  - pytorch=2.8.0
  - pip
  - pip:
    - gmsh==4.13.1